name: "lobster checks"
on:
  pull_request:
    paths:
      - "lobster.sh"
jobs:
  version-bump:
    name: Version Bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check version bump
        run: git diff origin/main | grep LOBSTER_VERSION
